embeddings {
    
    tensor_name: "Styles untrained"
    metadata_path: "styles_words.tsv"
    tensor_path: "init_styles_wv.tsv"
}

embeddings {

    tensor_name: "Styles only"
    tensor_path: "trained0_styles_wv.tsv"
    metadata_path: "styles_words.tsv"
}

embeddings {
    tensor_name: "MWE Styles"
    tensor_path: "styles_mwe.tsv"
    metadata_path: "mwe_meta_styles.tsv"
}
embeddings {

    tensor_name: "Styles trained on 3"
    tensor_path: "trained1_styles_wv.tsv"
    metadata_path: "styles_words.tsv"
}

embeddings {

    tensor_name: "Styles trained on 12"
    tensor_path: "all_12_styles_wv.tsv"
    metadata_path: "styles_words.tsv"
}

embeddings {

    tensor_name: "Links mwe"
    tensor_path: "links_mwe.tsv"
    metadata_path: "mwe_meta_links.tsv"
}

embeddings {

    tensor_name: "Ackroyd mwe"
    tensor_path: "ackroyd_mwe.tsv"
    metadata_path: "mwe_meta_ackroyd.tsv"
}
