embeddings: {
    tensor_name: "The-Murder-on-the-Links CBOW with lemmatization"
    tensor_path: "The-Murder-on-the-Links-CBOW-withlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-on-the-Links-CBOW-withlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-on-the-Links Skip-Gram with lemmatization"
    tensor_path: "The-Murder-on-the-Links-Skip-Gram-withlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-on-the-Links-Skip-Gram-withlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-on-the-Links CBOW without lemmatization"
    tensor_path: "The-Murder-on-the-Links-CBOW-withoutlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-on-the-Links-CBOW-withoutlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-on-the-Links Skip-Gram without lemmatization"
    tensor_path: "The-Murder-on-the-Links-Skip-Gram-withoutlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-on-the-Links-Skip-Gram-withoutlem.tsv"
}
embeddings: {
    tensor_name: "The-Mysterious-Affair-at-Styles CBOW with lemmatization"
    tensor_path: "The-Mysterious-Affair-at-Styles-CBOW-withlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Mysterious-Affair-at-Styles-CBOW-withlem.tsv"
}
embeddings: {
    tensor_name: "The-Mysterious-Affair-at-Styles Skip-Gram with lemmatization"
    tensor_path: "The-Mysterious-Affair-at-Styles-Skip-Gram-withlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Mysterious-Affair-at-Styles-Skip-Gram-withlem.tsv"
}
embeddings: {
    tensor_name: "The-Mysterious-Affair-at-Styles CBOW without lemmatization"
    tensor_path: "The-Mysterious-Affair-at-Styles-CBOW-withoutlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Mysterious-Affair-at-Styles-CBOW-withoutlem.tsv"
}
embeddings: {
    tensor_name: "The-Mysterious-Affair-at-Styles Skip-Gram without lemmatization"
    tensor_path: "The-Mysterious-Affair-at-Styles-Skip-Gram-withoutlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Mysterious-Affair-at-Styles-Skip-Gram-withoutlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-of-Roger-Ackroyd CBOW with lemmatization"
    tensor_path: "The-Murder-of-Roger-Ackroyd-CBOW-withlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-of-Roger-Ackroyd-CBOW-withlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-of-Roger-Ackroyd Skip-Gram with lemmatization"
    tensor_path: "The-Murder-of-Roger-Ackroyd-Skip-Gram-withlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-of-Roger-Ackroyd-Skip-Gram-withlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-of-Roger-Ackroyd CBOW without lemmatization"
    tensor_path: "The-Murder-of-Roger-Ackroyd-CBOW-withoutlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-of-Roger-Ackroyd-CBOW-withoutlem.tsv"
}
embeddings: {
    tensor_name: "The-Murder-of-Roger-Ackroyd Skip-Gram without lemmatization"
    tensor_path: "The-Murder-of-Roger-Ackroyd-Skip-Gram-withoutlem_mwe.tsv"
    metadata_path: "mwe_meta_The-Murder-of-Roger-Ackroyd-Skip-Gram-withoutlem.tsv"
}
