embeddings {
    
    tensor_name: "Styles untrained"
    metadata_path: "styles_words.tsv"
    tensor_path: "trained0_styles_wv.tsv"
}

embeddings {

    tensor_name: "Styles only"
    tensor_path: "trained0_styles_wv.tsv"
    metadata_path: "styles_words.tsv"
}

embeddings {

    tensor_name: "Styles all 3"
    tensor_path: "trained1_styles_wv.tsv"
    metadata_path: "styles_words.tsv"
}